import mop.*;
import org.aspectjml.ajmlrac.runtime.*;
import org.aspectjml.lang.annotation.*;
import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.JoinPoint.*;
import org.aspectjml.lang.annotation.After;
import org.aspectjml.lang.annotation.After.*;
import java.util.Map;
import java.util.Map.Entry;


privileged aspect AspectJMLRac_mop_Authenticator_OverrideGetPasswordAuthentication$fc95b0eb_6581_458a_89d9_b115f75115cf {

 declare precedence: AspectJMLRac$JMLRacPost4Project, AspectJMLRac_* , *;

  /** Generated by AspectJML to check the exceptional public postcondition of
   * method vioAuthenticator_OverrideGetPasswordAuthentication. */
   after (final org.aspectj.lang.JoinPoint joinPoint) throwing (Throwable rac$e) :
     call(static void mop.Authenticator_OverrideGetPasswordAuthenticationHandler.vioAuthenticator_OverrideGetPasswordAuthentication(org.aspectj.lang.JoinPoint)) && 
     !within(*..AspectJMLRac_*) && !within(AspectJMLRac_*) && args(joinPoint) {
           JMLChecker.rethrowJMLAssertionError(rac$e, "mop.Authenticator_OverrideGetPasswordAuthentication.vioAuthenticator_OverrideGetPasswordAuthentication(org.aspectj.lang.JoinPoint)");
           boolean rac$b = true;
           String rac$ErrorMsg = "";

  		   if (true) {
  		     if (rac$e instanceof java.lang.RuntimeException) {
  			   java.lang.RuntimeException jml$ex = (java.lang.RuntimeException) rac$e;
  			   boolean rac$b1 = true;
  			   try{			     
  			     rac$b1 = true;
  			   }   catch (JMLNonExecutableException rac$nonExec) {
  			     throw new JMLEvaluationError("Invalid Expression in \"mop.Authenticator_OverrideGetPasswordAuthentication.java\" by method mop.Authenticator_OverrideGetPasswordAuthentication.vioAuthenticator_OverrideGetPasswordAuthentication\nCaused by: "+rac$e);
  			   }
  			   if(!rac$b1) {
  			     if(rac$ErrorMsg.equals("")) {
  			       rac$ErrorMsg = "jml$ex";
  			     }
  			     else {
  			       rac$ErrorMsg += " and jml$ex";
  			     }
  			   }
  			   rac$b = rac$b && rac$b1;
           if(rac$ErrorMsg.indexOf("and") >= 0 ){
             rac$ErrorMsg += " are ";
           }
           else{
             rac$ErrorMsg += " is ";
           }
               JMLChecker.checkExceptionalPostcondition(rac$b,"by method mop.Authenticator_OverrideGetPasswordAuthentication.vioAuthenticator_OverrideGetPasswordAuthentication regarding code at \nFile \"mop.Authenticator_OverrideGetPasswordAuthentication.java\""+"\n\t"+rac$ErrorMsg+rac$e, "jml$ex", true, 1, "mop.Authenticator_OverrideGetPasswordAuthentication.vioAuthenticator_OverrideGetPasswordAuthentication(org.aspectj.lang.JoinPoint)", rac$e);
  		 }
  		   }
  	 }





  /** Generated by AspectJML to mark/annotate all advice method in AspectJML */
  declare @method: public static void mop.Authenticator_OverrideGetPasswordAuthenticationHandler.vioAuthenticator_OverrideGetPasswordAuthentication(org.aspectj.lang.JoinPoint): @org.aspectjml.lang.annotation.Advice;


  /** Generated by AspectJML to activate the crosscutting concern modularization */
  @org.aspectj.lang.annotation.Aspect
  public static class AspectJMLInnerCC_mop_Authenticator_OverrideGetPasswordAuthentication{

  /** Generated by AspectJML to modularize a crosscutting structure for
   * the Java members intercepted by vioAuthenticator_OverrideGetPasswordAuthentication AspectJML/Advice. */
  @org.aspectj.lang.annotation.After("staticinitialization(java.net.Authenticator+) && !within(*..AspectJMLInnerCC_*) && !within(AspectJMLInnerCC_*) && !@annotation(ExcludeAdvising) && !@annotation(Sealed) && !cflowbelow(staticinitialization(java.net.Authenticator+)) && !cflow(execution(public static void mop.Authenticator_OverrideGetPasswordAuthentication.vioAuthenticator_OverrideGetPasswordAuthentication(org.aspectj.lang.JoinPoint)))")
  public void vioAuthenticator_OverrideGetPasswordAuthentication (final org.aspectj.lang.JoinPoint joinPoint) {//#public static void mop.Authenticator_OverrideGetPasswordAuthentication.vioAuthenticator_OverrideGetPasswordAuthentication(org.aspectj.lang.JoinPoint)#'mop.Authenticator_OverrideGetPasswordAuthentication' (Authenticator_OverrideGetPasswordAuthentication.java:9)
//      if(JMLChecker.checkJP(joinPoint, true, "mop.Authenticator_OverrideGetPasswordAuthentication", true, true, true))
       mop.Authenticator_OverrideGetPasswordAuthenticationHandler.vioAuthenticator_OverrideGetPasswordAuthentication(joinPoint);
  }

  }
}
